version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: REDACTED
    volumes:
      - ./stuff/init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: ./stuff
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./stuff/index.php:/var/www/html/index.php

